### ISSUE TITLE
Have it fetch and use the one from the following URL

### ISSUE THREAD

**Issue by Zero3K** [mziyut/disposable-email-domains-js#71]
https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/refs/heads/main/disposable_email_blocklist.conf

That way you won't have to update it in this repository.

**Comment by mziyut** [comment]
I thought the same thing at first, but decided that communication with the outside world should be avoided as much as possible, so I took the form of referencing it in the current Submodule.
(As it is not always safe to retrieve data externally.)

I am sorry, but I do not plan to implement it based on the suggestions I received.

**Comment by Zero3K** [comment]
Okay.
